-- MySQL Script generated by MySQL Workbench
-- 08/24/16 18:14:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pretrip
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pretrip
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pretrip` DEFAULT CHARACTER SET utf8 ;
USE `pretrip` ;

-- -----------------------------------------------------
-- Table `pretrip`.`contas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pretrip`.`contas` (
  `ID_CONTA` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `SALDO` DOUBLE NOT NULL COMMENT '',
  PRIMARY KEY (`ID_CONTA`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pretrip`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pretrip`.`enderecos` (
  `ID_ENDERECO` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `NUM` INT(11) NULL DEFAULT NULL COMMENT '',
  `COMPLEMENTO` INT(11) NULL DEFAULT NULL COMMENT '',
  `RUA` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `BAIRRO` VARCHAR(80) NULL DEFAULT NULL COMMENT '',
  `CIDADE` VARCHAR(30) NULL DEFAULT NULL COMMENT '',
  `ESTADO` VARCHAR(40) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`ID_ENDERECO`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pretrip`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pretrip`.`empresas` (
  `ID_EMPRESA` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `ID_ENDERECO` INT(11) NULL DEFAULT NULL COMMENT '',
  `CNPJ` CHAR(14) NULL DEFAULT NULL COMMENT '',
  `RAZAO_SOCIAL` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `NM_FANTASIA` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`ID_EMPRESA`)  COMMENT '',
  INDEX `fk_endereco_empresa_idx` (`ID_ENDERECO` ASC)  COMMENT '',
  CONSTRAINT `fk_endereco_empresa`
    FOREIGN KEY (`ID_ENDERECO`)
    REFERENCES `pretrip`.`enderecos` (`ID_ENDERECO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pretrip`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pretrip`.`eventos` (
  `ID_EVENTO` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `NM_EVENTO` VARCHAR(130) NULL DEFAULT NULL COMMENT '',
  `TAGS` VARCHAR(130) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`ID_EVENTO`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pretrip`.`veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pretrip`.`veiculos` (
  `ID_VEICULO` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `MODELO` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `PLACA` VARCHAR(8) NULL DEFAULT NULL COMMENT '',
  `TIPO` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  `QTD_LUGARES` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`ID_VEICULO`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pretrip`.`viagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pretrip`.`viagens` (
  `ID_VIAGEM` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `ID_VEICULO` INT(11) NULL DEFAULT NULL COMMENT '',
  `ID_EMPRESA` INT(11) NULL DEFAULT NULL COMMENT '',
  `PRECO_PASSAGEM` DOUBLE NULL DEFAULT NULL COMMENT '',
  `DS_VIAGEM` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `DT_SAIDA` DATETIME NULL DEFAULT NULL COMMENT '',
  `DT_CHEGADA_ESPERADA` DATETIME NULL DEFAULT NULL COMMENT '',
  `LUGARES_DISPONIVEIS` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`ID_VIAGEM`)  COMMENT '',
  INDEX `fk_veiculos_viagens_idx` (`ID_VEICULO` ASC)  COMMENT '',
  INDEX `fk_empresa_viagens_idx` (`ID_EMPRESA` ASC)  COMMENT '',
  CONSTRAINT `fk_empresa_viagens`
    FOREIGN KEY (`ID_EMPRESA`)
    REFERENCES `pretrip`.`empresas` (`ID_EMPRESA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veiculos_viagens`
    FOREIGN KEY (`ID_VEICULO`)
    REFERENCES `pretrip`.`veiculos` (`ID_VEICULO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pretrip`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pretrip`.`pedidos` (
  `ID_PEDIDO` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `ID_VIAGEM` INT(11) NULL DEFAULT NULL COMMENT '',
  `DT_REALIZACAO` DATETIME NULL DEFAULT NULL COMMENT '',
  `QTD` INT(11) NULL DEFAULT NULL COMMENT '',
  `PRECO_TOTAL` DOUBLE NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`ID_PEDIDO`)  COMMENT '',
  INDEX `fk_viagens_pedidos_idx` (`ID_VIAGEM` ASC)  COMMENT '',
  CONSTRAINT `fk_viagens_pedidos`
    FOREIGN KEY (`ID_VIAGEM`)
    REFERENCES `pretrip`.`viagens` (`ID_VIAGEM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pretrip`.`pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pretrip`.`pessoas` (
  `ID_PESSOA` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `NM_PESSOA` VARCHAR(255) NOT NULL COMMENT '',
  `TELEFONE` INT(11) NOT NULL COMMENT '',
  `CPF` INT(11) NULL DEFAULT NULL COMMENT '',
  `DATA_NASC` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `ID_CONTA` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`ID_PESSOA`)  COMMENT '',
  INDEX `fk_conta_pessoa_idx` (`ID_CONTA` ASC)  COMMENT '',
  CONSTRAINT `fk_conta_pessoa`
    FOREIGN KEY (`ID_CONTA`)
    REFERENCES `pretrip`.`contas` (`ID_CONTA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pretrip`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pretrip`.`usuarios` (
  `ID_USUARIO` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `LOGIN` VARCHAR(20) NOT NULL COMMENT '',
  `SENHA` VARCHAR(20) NULL DEFAULT NULL COMMENT '',
  `IS_ADMIN` TINYINT(4) NULL DEFAULT NULL COMMENT '',
  `ID_PESSOA` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`ID_USUARIO`)  COMMENT '',
  INDEX `fk_pessoa_usuario_idx` (`ID_PESSOA` ASC)  COMMENT '',
  CONSTRAINT `fk_pessoa_usuario`
    FOREIGN KEY (`ID_PESSOA`)
    REFERENCES `pretrip`.`pessoas` (`ID_PESSOA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pretrip`.`usuario_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pretrip`.`usuario_pedido` (
  `ID_USUARIO` INT(11) NOT NULL COMMENT '',
  `ID_PEDIDO` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`ID_USUARIO`, `ID_PEDIDO`)  COMMENT '',
  INDEX `fk_pedido_usuarioPedido_idx` (`ID_PEDIDO` ASC)  COMMENT '',
  CONSTRAINT `fk_pedido_usuarioPedido`
    FOREIGN KEY (`ID_PEDIDO`)
    REFERENCES `pretrip`.`pedidos` (`ID_PEDIDO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_usuarioPedido`
    FOREIGN KEY (`ID_USUARIO`)
    REFERENCES `pretrip`.`usuarios` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pretrip`.`usuario_viagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pretrip`.`usuario_viagem` (
  `ID_USUARIO` INT(11) NOT NULL COMMENT '',
  `ID_VIAGEM` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`ID_USUARIO`, `ID_VIAGEM`)  COMMENT '',
  INDEX `fk_viagem_usuarioViagem_idx` (`ID_VIAGEM` ASC)  COMMENT '',
  CONSTRAINT `fk_usuario_usuarioViagem`
    FOREIGN KEY (`ID_USUARIO`)
    REFERENCES `pretrip`.`usuarios` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viagem_usuarioViagem`
    FOREIGN KEY (`ID_VIAGEM`)
    REFERENCES `pretrip`.`viagens` (`ID_VIAGEM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pretrip`.`viagem_evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pretrip`.`viagem_evento` (
  `ID_VIAGEM` INT(11) NOT NULL COMMENT '',
  `ID_EVENTO` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`ID_VIAGEM`, `ID_EVENTO`)  COMMENT '',
  INDEX `fk_evento_eventos_idx` (`ID_EVENTO` ASC)  COMMENT '',
  CONSTRAINT `fk_evento_eventos`
    FOREIGN KEY (`ID_EVENTO`)
    REFERENCES `pretrip`.`eventos` (`ID_EVENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viagem_viagemEvento`
    FOREIGN KEY (`ID_VIAGEM`)
    REFERENCES `pretrip`.`viagens` (`ID_VIAGEM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
